config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :users

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:taskName, :taskDescr)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:userid, :FirstName, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ping.rb
require 'concurrent'

require "concurrent-edge"

Channel = Concurrent::Channel

## Go by Example: Unbuffered Channel
# https://gobyexample.com/channels

messages = Channel.new # unbuffered

Channel.go do
  messages.put 'ping'
end

msg = messages.take
puts msg

__END__
ping

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tickers.rb
require 'concurrent-edge'
Channel = Concurrent::Channel

## Go by Example: Tickers
# https://gobyexample.com/tickers

ticker = Channel.ticker(0.5)
Channel.go do
  ticker.each do |tick|
    print "Tick at #{tick}\n" if tick
  end
end

sleep(5.0)
ticker.stop
print "Ticker stopped\n"

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="assets/favicon.ico">

  <title>AngularVenkat</title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>


  <!--<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>-->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<div ng-app="todoapp">
  <div ng-controller="TaskController as mySaveTaskController">
    <%= form_for(@task) do |f| %>
        <% if @task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @task.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :taskName %><br>
          <%= f.text_field :taskName %>
        </div>
        <div class="field">
          <%= f.label :taskDescr %><br>
          <%= f.text_field :taskDescr %>
        </div>
        {{mySaveTaskController.task.taskName}}
        <div class="actions">
          <input type="submit" ng-disabled="mySaveTaskController.validateTask();" ng-click="mySaveTaskController.addTask();" value="Create"/>
        </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div ng-app="todoapp">
  <div ng-controller="TaskController as taskController">
   Total tasks to do is: {{ taskController.tasks.length }}

  </div>
</div>
<h1>Listing Tasks</h1>

<table>
  <thead>
  <tr>
    <th>Taskname</th>
    <th>Taskdescr</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= task.taskName %></td>
        <td><%= task.taskDescr %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Taskname:</strong>
  <%= @task.taskName %>
</p>

<p>
  <strong>Taskdescr:</strong>
  <%= @task.taskDescr %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br>
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div ng-app="myapp">
  <p id="notice"><%= notice %></p>
  <h1>Listing Users</h1>
  <p>The value is {{1+1}}</p>
  <div ng-controller="MyController as myController">
    <p>
      Hello {{ myController.greet() }}
    </p>
    <br>
    First Name: <input ng-model="myController.firstName" ng-model-options="{ updateOn: 'blur' }"/>
    </br>
    <br>
    Last Name: <input ng-model="myController.lastName" ng-model-options="{ updateOn: 'blur' }"/>
    </br>
    <br>
    {{myController.greet()}} Full Name: {{ myController.getFullName() }}
    </br>
    {{myController.count}}
    <button ng-click="myController.clickMe();">OK Here</button>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @user.userid %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.FirstName %>
</p>

<p>
  <strong>String:</strong>
  <%= @user.string %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>